package analise;

public class Token {

    public static final int VOID = 0;
    public static final int MAIN = 1;
    public static final int INT = 2;
    public static final int FLOAT = 3;
    public static final int PRINT = 4;
    public static final int SCANF = 5;
    public static final int ATRIBUICAO = 6;
    public static final int PONTO_VIRGULA = 7;
    public static final int ABRE_CHAVE = 8;
    public static final int FECHA_CHAVE = 9;
    public static final int ABRE_PARENTESE = 10;
    public static final int FECHA_PARENTESE = 11;
    public static final int ADICAO = 12;
    public static final int VIRGULA = 13;
    public static final int PONTOFINAL = 14;
    public static final int NUM_INTEIRO = 15;
    public static final int VARIAVEL = 16;
    public static final int CHAR = 17;
    public static final int ERRO_DESCONHECIDO = 18;
    public static final int NUM_DECIMAL = 19;
    public static final int FOR = 20;
    public static final int FOR_LOOP = 21;
    public static final int COUT = 22;
    public static final int INSERCAO = 23;
    public static final int STRING = 24;
    public static final int VAZIO = 25;
    public static final int ASPASDUPLAS = 26;
    public static final int IF = 27;
    public static final int ELSE = 28;
    public static final int MAIORQUE = 29;
    public static final int MULTIPLICACAO = 30;
    public static final int STRINGFORMATO = 31;
    public static final int ENDERECO_DA_VARIAVEL = 32;
    public static final int SCANF_FUNCAO = 33;
    public static final int OU = 34;
    public static final int E = 35;
    public static final int MENORQUE = 36;
    public static final int COMENTARIOS = 37;
    public static final int RETURN = 38;
    public static final int MENOR_IGUAL = 39;
    public static final int DEFAULT = 40;
    public static final int BREAK = 41;
    public static final int DO = 42;
    public static final int SWITCH = 43;
    public static final int CASE = 44;
    public static final int CLEAR = 45;
    public static final int WHILE = 46;
    public static final int QUEBRA_DE_LINHA = 47;
    public static final int MATRIZ = 48;
}
